#!/usr/bin/env python3
"""
Verify zero-knowledge proofs for Noir circuits using Barretenberg.
This script verifies proofs generated by the proof generation script.
"""

import os
import subprocess
import sys
import time
import json
from pathlib import Path

# Configuration
CIRCUIT_DIR = "age_verification"
PROOFS_DIR = Path(CIRCUIT_DIR) / "proofs"

def find_bb_binary():
    """Find the bb binary in local and common locations."""
    # Check local repository installation first
    repo_root = Path(__file__).parent.parent
    local_bb = repo_root / ".local" / "bin" / "bb"
    if local_bb.exists():
        return local_bb

    # Also check PATH and common locations
    possible_locations = [
        Path.home() / ".bb" / "bb",
        Path.home() / ".local" / "bin" / "bb",
        Path("/usr/local/bin/bb"),
        Path("/opt/homebrew/bin/bb"),
    ]

    try:
        result = subprocess.run(["which", "bb"], capture_output=True, text=True)
        if result.returncode == 0:
            bb_path = Path(result.stdout.strip())
            if bb_path.exists():
                return bb_path
    except Exception:
        pass

    # Check common locations
    for location in possible_locations:
        if location.exists() and location.is_file():
            return location

    return None

def check_dependencies():
    """Check if required tools and files are available."""
    print("🔍 Checking dependencies...")

    # Check for bb (Barretenberg)
    bb_binary = find_bb_binary()
    if not bb_binary:
        print("❌ bb binary not found")
        print("Run 'python proof_system/install_barretenberg.py' first.")
        return None

    try:
        result = subprocess.run([str(bb_binary), "--version"], capture_output=True, text=True)
        print(f"✅ barretenberg: {result.stdout.strip() if result.returncode == 0 else 'installed'}")
    except Exception:
        print("⚠️  bb binary found but version check failed")

    # Check for proof files
    if not PROOFS_DIR.exists():
        print(f"❌ Proofs directory {PROOFS_DIR} not found")
        print("Run 'python proof_system/generate_proof.py' first.")
        return None

    proof_file = PROOFS_DIR / "circuit" / "proof"
    vk_file = PROOFS_DIR / "verification_key" / "vk"

    if not proof_file.exists():
        print(f"❌ Proof file not found: {proof_file}")
        print("Run 'python proof_system/generate_proof.py' first.")
        return None

    if not vk_file.exists():
        print(f"❌ Verification key not found: {vk_file}")
        print("Run 'python proof_system/generate_proof.py' first.")
        return None

    print(f"✅ Proof file found: {proof_file}")
    print(f"✅ Verification key found: {vk_file}")

    return bb_binary

def run_command_with_timing(cmd, description):
    """Run a command and measure execution time."""
    print(f"🔄 {description}...")
    start_time = time.time()

    try:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True
        )
        end_time = time.time()
        duration = end_time - start_time

        if result.returncode == 0:
            print(f"✅ {description}: {duration:.3f}s")
            return {
                'success': True,
                'duration': duration,
                'stdout': result.stdout,
                'stderr': result.stderr
            }
        else:
            print(f"❌ {description} failed ({duration:.3f}s):")
            print(f"   Error: {result.stderr}")
            return {
                'success': False,
                'duration': duration,
                'stdout': result.stdout,
                'stderr': result.stderr
            }
    except Exception as e:
        end_time = time.time()
        duration = end_time - start_time
        print(f"❌ {description} failed ({duration:.3f}s): {e}")
        return {
            'success': False,
            'duration': duration,
            'error': str(e)
        }

def verify_proof(bb_binary):
    """Verify the zero-knowledge proof using Barretenberg."""
    proof_file = PROOFS_DIR / "circuit" / "proof"
    vk_file = PROOFS_DIR / "verification_key" / "vk"

    cmd = (
        f'"{bb_binary}" verify '
        f'--scheme ultra_honk '
        f'-k "{vk_file}" '
        f'-p "{proof_file}"'
    )

    result = run_command_with_timing(
        cmd,
        "Zero-knowledge proof verification"
    )

    return result

def analyze_proof_files():
    """Analyze the sizes and details of proof files."""
    print("\n📊 Proof File Analysis")
    print("-" * 30)

    proof_file = PROOFS_DIR / "circuit" / "proof"
    vk_file = PROOFS_DIR / "verification_key" / "vk"

    if proof_file.exists():
        proof_size = proof_file.stat().st_size
        print(f"📦 Proof file: {proof_size} bytes ({proof_size/1024:.2f} KB)")

    if vk_file.exists():
        vk_size = vk_file.stat().st_size
        print(f"🔑 Verification key: {vk_size} bytes ({vk_size/1024:.2f} KB)")

    # Check if proof info exists
    info_file = PROOFS_DIR / "proof_info.json"
    if info_file.exists():
        try:
            with open(info_file, 'r') as f:
                proof_info = json.load(f)
            print(f"ℹ️  Proof generated: {time.ctime(proof_info['timestamp'])}")

            # Show generation times if available
            if 'results' in proof_info:
                results = proof_info['results']
                if 'proof_generation' in results and 'duration' in results['proof_generation']:
                    gen_time = results['proof_generation']['duration']
                    print(f"⏱️  Generation time: {gen_time:.3f}s")

        except Exception as e:
            print(f"⚠️  Could not read proof info: {e}")

def save_verification_results(results):
    """Save verification results to JSON file."""
    verification_info = {
        'timestamp': time.time(),
        'verification_result': results
    }

    info_file = PROOFS_DIR / "verification_info.json"
    with open(info_file, 'w') as f:
        json.dump(verification_info, f, indent=2)

    print(f"💾 Verification info saved to {info_file}")

def run_complete_verification(bb_binary):
    """Run verification with additional checks and analysis."""
    print("🔍 Complete Proof Verification")
    print("=" * 50)

    # Analyze proof files first
    analyze_proof_files()

    # Run verification
    print("\n🔐 Proof Verification")
    print("-" * 30)

    verify_result = verify_proof(bb_binary)

    if verify_result['success']:
        print("\n✅ PROOF VERIFICATION SUCCESSFUL!")
        print("🎉 The zero-knowledge proof is valid!")
        print("   This confirms:")
        print("   • The prover knew valid credential data")
        print("   • The credential was signed by the trusted issuer")
        print("   • The age requirement was met")
        print("   • No personal information was revealed")

        # Show timing
        print(f"\n⏱️  Verification completed in {verify_result['duration']:.3f}s")

    else:
        print("\n❌ PROOF VERIFICATION FAILED!")
        print("💥 The zero-knowledge proof is invalid or corrupted")
        if 'stderr' in verify_result and verify_result['stderr']:
            print(f"   Error details: {verify_result['stderr']}")

    return verify_result

def main():
    """Main verification workflow."""
    print("🛡️  Noir Zero-Knowledge Proof Verification")
    print("=" * 50)

    bb_binary = check_dependencies()
    if not bb_binary:
        sys.exit(1)

    # Run complete verification
    result = run_complete_verification(bb_binary)

    # Save results
    save_verification_results(result)

    # Summary and next steps
    print("\n" + "=" * 50)
    if result['success']:
        print("🎯 VERIFICATION COMPLETE - PROOF IS VALID")
        print("\n💡 What this means:")
        print("   ✓ Age verification was proven without revealing personal data")
        print("   ✓ Credential signature from trusted issuer was verified")
        print("   ✓ Zero-knowledge property maintained throughout")
        print("\n🚀 Next steps:")
        print("   • Deploy the verification key to a smart contract")
        print("   • Integrate proof verification into your application")
        print("   • Run benchmarks to analyze performance")
    else:
        print("🚨 VERIFICATION FAILED - PROOF IS INVALID")
        print("\n🔧 Troubleshooting:")
        print("   • Regenerate the proof with generate_proof.py")
        print("   • Check that input data hasn't been corrupted")
        print("   • Ensure the circuit hasn't been modified")

    sys.exit(0 if result['success'] else 1)

if __name__ == "__main__":
    main()